In [ ]:
from IPython.display import HTML
HTML('''
    <style> body {font-family: "Roboto Condensed Light", "Roboto Condensed";} h2 {padding: 10px 12px; background-color: #E64626; position: static; color: #ffffff; font-size: 40px;} .text_cell_render p { font-size: 15px; } .text_cell_render h1 { font-size: 30px; } h1 {padding: 10px 12px; background-color: #E64626; color: #ffffff; font-size: 40px;} .text_cell_render h3 { padding: 10px 12px; background-color: #0148A4; position: static; color: #ffffff; font-size: 20px;} h4:before{ 
    content: "@"; font-family:"Wingdings"; font-style:regular; margin-right: 4px;} .text_cell_render h4 {padding: 8px; font-family: "Roboto Condensed Light"; position: static; font-style: italic; background-color: #FFB800; color: #ffffff; font-size: 18px; text-align: center; border-radius: 5px;}input[type=submit] {background-color: #E64626; border: solid; border-color: #734036; color: white; padding: 8px 16px; text-decoration: none; margin: 4px 2px; cursor: pointer; border-radius: 20px;}</style>
''')

# Income

In [1]:
# Import necessary Libraries
import pandas as pd
import matplotlib.pyplot as plt

In [69]:
#Reading in the Data into a DataFrame, as it has no geometry info
relative_path = "Income.csv"
income_data = pd.read_csv(relative_path)
income_index = list(income_data['sa2_code21'])
income_data.set_index('sa2_code21',inplace=True)
income_data.head(5)

,sa2_name,earners,median_age,median_income,mean_income
sa2_code21,,,,,
101021007,Braidwood,2467,51,46640,68904
101021008,Karabar,5103,42,65564,69672
101021009,Queanbeyan,7028,39,63528,69174
101021010,Queanbeyan - East,3398,39,66148,74162
101021012,Queanbeyan West - Jerrabomberra,8422,44,78630,91981

The following are numerous checks for different types of null values (Null, Na, Non-Numeric, Negative)

In [ ]:
# Initial Test for null values
for col in list(income_data.columns)[2:6]: #This selects earners, median_age, median_income and mean_income
    size = len(income_data[income_data[col].isnull()]) #Number of Null values
    size += len(income_data[income_data[col].isna()]) #Number of NA values
    print(size)

In [102]:
#This code finds all entries which are non-numeric in the columns we expect to have numbers
problem_rows = [] #Keep a list of all rows with null values
for row in income_index:
    for col in list(income_data.columns)[2:6]: #This selects earners, median_age, median_income and mean_income
        try:
            income_data[col][row] = pd.to_numeric(income_data[col][row]) #Tries to make it a number, if it fails it prints the line
            if income_data[col][row] < 0: #Tests for negative numbers which are also an irregularity
                problem_rows.append(row)
            break
        except:
            problem_rows.append(row)
            break
income_data.loc[problem_rows]

,sa2_name,earners,median_age,median_income,mean_income
sa2_code21,,,,,
103031075,Wollangambe - Wollemi,np,np,np,np
107011133,Port Kembla Industrial,np,np,np,np
107021135,Illawarra Catchment Reserve,np,np,np,np
108031161,Lord Howe Island,np,np,np,np
118011342,Centennial Park,np,np,np,np
123021439,Holsworthy Military Area,np,np,np,np
124021456,Blue Mountains - South,np,np,np,np

# Comparisons to Population

Note there is a difference in size between this data set and the population dataset, and so by importing that dataset too we can check which ones are missing.

In [8]:
relative_path = "Population.csv"
population_data = pd.read_csv(relative_path)

In [20]:
pop_codes = list(population_data['sa2_code'])
inc_codes = list(income_data['sa2_code21'])
all_codes = set(pop_codes + inc_codes)
len(all_codes)

missing_codes = list(set(all_codes).difference(set(pop_codes)))
missing_codes

[103021062,
 103021063,
 103021064,
 103021065,
 103021066,
 103021067,
 103021068,
 103021069,
 106031119,
 106031120,
 106031121,
 106031122,
 106031123,
 106031124,
 106031125,
 112031250,
 112031251,
 112031252,
 112031253,
 112031254,
 103041076,
 103041077,
 103041078,
 103041079,
 113011256,
 113011257,
 113011258,
 113011259,
 107011131,
 107011132,
 107011133,
 107011134,
 110021190,
 110021191,
 110021192,
 110021193,
 110021194,
 104021083,
 104021084,
 104021085,
 104021086,
 113031263,
 113031264,
 113031265,
 113031266,
 113031267,
 113031268,
 113031269,
 113031270,
 113031271,
 107031136,
 107031137,
 107031138,
 107031139,
 107031140,
 107031141,
 107031142,
 110041199,
 110041200,
 110041201,
 110041202,
 110041203,
 110041204,
 110041205,
 114011272,
 114011273,
 114011274,
 114011275,
 114011276,
 114011277,
 114011278,
 114011279,
 114011280,
 114011281,
 114011282,
 101051539,
 101051540,
 114011283,
 108011151,
 108011152,
 108011153,
 108011154,
 111021215,
 111021216,
 111021217,
 111021218,
 111021219,
 111021220,
 111021221,
 105021097,
 105021098,
 108031161,
 101031013,
 108051167,
 108051168,
 108051169,
 108051170,
 108051171,
 109011172,
 109011173,
 109011174,
 109011175,
 109011176,
 101031014,
 101031015,
 101031016,
 106021614,
 106021615,
 106021616,
 106021617,
 106021618,
 103011059,
 103011060,
 103011061,
 106021114,
 106021116,
 112021244,
 112021245,
 112021246,
 112021247,
 112021248,
 112021249,
 107041548,
 107041549,
 109031180,
 109031181,
 109031182,
 109031183,
 109031184,
 109031185,
 103011612,
 103011613,
 103031070,
 103031071,
 103031072,
 103031073,
 103031074,
 103031075,
 106041126,
 106041127,
 106041128,
 106041129,
 110011186,
 110011187,
 110011188,
 110011189,
 112031550,
 112031551,
 112031552,
 104011080,
 104011081,
 104011082,
 113021260,
 113021261,
 113021262,
 107021135,
 101021007,
 101021008,
 101021009,
 101021010,
 101021012,
 107031143,
 110031195,
 110031196,
 110031197,
 110031198,
 107041144,
 107041145,
 107041146,
 107041147,
 107041148,
 101041017,
 107041150,
 101041018,
 101041019,
 101041020,
 101041021,
 101041022,
 101041023,
 101041024,
 101041025,
 101041026,
 101041027,
 111011206,
 111011207,
 111011208,
 111011209,
 111011210,
 111011211,
 111011212,
 111011213,
 111011214,
 108041619,
 108041620,
 105011092,
 105011093,
 105011094,
 105011095,
 105011096,
 108021155,
 114021284,
 101061541,
 101061542,
 101061543,
 101061544,
 114021285,
 114021286,
 114021287,
 114021288,
 114021289,
 108021157,
 108021158,
 108021159,
 108021160,
 101021610,
 101021611,
 111031222,
 111031223,
 111031224,
 111031225,
 111031226,
 111031227,
 111031228,
 111031229,
 111031230,
 111031231,
 111031232,
 104021087,
 111031234,
 111031233,
 104021088,
 111031235,
 105031101,
 105031102,
 105031103,
 104021089,
 108041162,
 105031106,
 108041164,
 108041165,
 108041166,
 104021090,
 104021091,
 105031099,
 107011545,
 105031100,
 107011546,
 107011547,
 106011107,
 106011108,
 106011109,
 106011110,
 106011111,
 106011112,
 106011113,
 112011236,
 112011237,
 112011238,
 112011239,
 112011240,
 105031104,
 112011241,
 112011242,
 112011243,
 105031105,
 109021177,
 109021178,
 109021179,
 108021156]